### ISSUE TITLE
Tiamat 0.4.1 fails to start.

### ISSUE THREAD

**Issue by MoraFermi** [virenerus/tabletoptool#15] opened 2014-07-20 19:30 UTC
This is a Ubuntu 14.04 with Oracle Java 8 and 7:

mora@trusty-build:~/Hubic/Soft/t3-0.4.1$ /usr/lib/jvm/java-8-oracle/jre/bin/java -Xss512K -Xmx1024M -jar t3.jar
Exception in thread "main" java.lang.ExceptionInInitializerError
    at com.jidesoft.plaf.xerto.XertoMetalUtils.initComponentDefaults(Unknown Source)
    at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(Unknown Source)
    at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(Unknown Source)
    at com.t3.client.TabletopTool.main(TabletopTool.java:1237)
Caused by: java.lang.NullPointerException
    at com.jidesoft.plaf.xerto.XertoUtils.updateColors(Unknown Source)
    at com.jidesoft.plaf.xerto.XertoUtils.<clinit>(Unknown Source)
    ... 4 more

Except for an empty log.txt file, there is nothing in ~/.tabletoptool directory.

The same happens with 0.3.8; 0.4.1 works well on a 12.04 based system.

**Comment by virenerus** [comment] 2014-07-20 19:54
This bug seems to be a problem with the jide libraries and xerto. It will probably already be fixed in a newer jide version. Can't download them though until they approved us as an open source license for the project.

**Comment by czarnoff** [comment] 2014-07-23 21:59
On ubuntu 14.04, Java 7_65, I get this error when I run the program using the unity or gnome desktop manager.  Everything works fine if I start the program using KDE.  If I use the "awesome" wm, I get a gray box.  The menu works, but nothing else is drawn correctly.

**Comment by virenerus** [comment] 2014-07-24 19:23
Jide approval was really quick and easy. Nice support there. Could you please check if the problem is the same with [this](https://github.com/virenerus/tabletoptool/raw/c0eb526ae57f81038dd8f4b48a86091b00c29686/tiamat-build/t3.zip) version? If it doesn't we will have the fun of again diving into the very beautiful world of Swing L&Fs -.- Ugh

**Comment by MoraFermi** [comment] 2014-07-26 10:58
Unfortunately, this new version does _not_ solve the problem.

On the up side, as @czarnoff mentioned, this problem only manifests on Unity, which means it's directly related to the way Unity yanks the menu bar out of app's window and sticks it into a bar on top of the screen, a la MacOS 9.

I would mark this bug as "low priority" now and stick a warning to all Ubuntu/Unity users right on top of download page.

**Comment by virenerus** [comment] 2014-07-26 11:33
Mh. But that is really bugging me. 
Well with the new jide version we also got the sources so I will be able to debug into this as soon as I have an ubuntu vm set up.

**Comment by virenerus** [comment] 2014-07-26 17:18
Okay, so the Xerto style of Jide is simply not compatible with Unity. But I don't want the default styles from jide, because under Windows they are ugly. So now Windows gets Xerto and Mac and Unix get the one that Jide selects.

**Closed as completed** 2014-07-26 17:19 UTC
Labels: bug
